### ISSUE TITLE
Fails on load with atom-shell branch of LT

### ISSUE THREAD

**Issue by rundis** [cldwalker/gitbeam#1]
Culprit:
https://github.com/cldwalker/gitbeam/blob/master/src/lt/plugins/gitbeam/util.cljs#L78

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 2 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/gitbeam#1). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Thanks for the reminder :)
